### ISSUE TITLE
[V3] Fix exercise names, fix documents, fix all the things

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#1017]
I know what needs to be done, so... there's that. This issue is just so I can write things down between times I can work on this, and so other people could pick it up should something happen to me (nothing planned!, just in case).

I will also reference this issue from PRs related.

- [x] Lucian's Lucious Lasagna (`basics`): ~#1018~ 
- [x] Annalyn's Infiltration (`booleans`): ~#1020~
- [x] Freelancer Rates (`numbers`): ~#1021~
- [x] Poetry Club Door Policy (`strings`): ~#1043~ ~https://github.com/exercism/javascript-test-runner/pull/36~
- [x] Elyses Enchantments (`arrays`) : ~#1071~
- [ ] Elyses Analytic Enchantments  (`array-analysis`) 
- [x] Elyses Destructured Enchantments (`array-destructuring`)
- [x] Elyses Looping Enchantments (`array-loops`) #1097
- [ ] Elyses Transformative Enchantments (`array-transformations`)
- [x] Translation Service (`promises`) ~#1071~ (needs another issue)

## IF YOU ARE WORKING ON THIS

Please let me know in this issue so I don't work on it. Anything listed above is being worked on by _someone_. I tick them off once there is a PR.

**Comment by angelikatyborska** [comment]
I'm going to work this weekend on "fixing everything" about Elyses Destructured Enchantments

**Comment by junedev** [comment]
Just for reference, `errors` also needs to be fixed as @angelikatyborska noted. In particular it is missing the exercise entry in the global config.json file.

**Comment by junedev** [comment]
I created more descriptive issues for the remaining items on the list above, closing this one.
#1325 
#1326 

That way it is easier for people to see that there are already open issues for these exercises and to add comments there instead of opening a new issue.
