### ISSUE TITLE
Checklist: core exercise mentor notes

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#591]
Mentor notes should be written here: [website-copy/tracks/javascript](https://github.com/exercism/website-copy/tree/master/tracks/javascript/exercises)

- [x] [two-fer](https://github.com/exercism/website-copy/tree/master/tracks/javascript/exercises/two-fer) ~(needs update)~
- [x] [resistor-color](https://github.com/exercism/website-copy/tree/master/tracks/javascript/exercises/resistor-color)
- [x] [resistor-color-duo](https://github.com/exercism/website-copy/tree/master/tracks/javascript/exercises/resistor-color-duo)
- [x] [gigasecond](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/gigasecond/mentoring.md)
- [x] [rna-transcription](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/rna-transcription/mentoring.md) (needs update)
- [x] [bob](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/bob/mentoring.md)
- [x] [pangram](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/pangram/mentoring.md)
- [x] [space-age](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/space-age/mentoring.md)
- [x] [matrix](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/matrix/mentoring.md)
- [x] [linked-list](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/linked-list/mentoring.md)
- [x] [grade-school](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/grade-school/mentoring.md)
- [x] [robot-name](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/robot-name/mentoring.md)
- [x] [pascals-triangle](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/pascals-triangle/mentoring.md)
- [x] [simple-cipher](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/simple-cipher/mentoring.md)
- [x] [wordy](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/wordy/mentoring.md)
- [x] [secret-handshake](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/secret-handshake/mentoring.md)
- [x] [list-ops](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/list-ops/mentoring.md)

Non-core exercises with notes:
- [x] [leap](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/leap/mentoring.md)
- [hamming](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/hamming/mentoring.md)
- [etl](https://github.com/exercism/website-opy/tree/master/tracks/javascript/exercises/etl)

If you are writing mentor notes, please dibs it here so people don't do double work! Check the open PRs for [mentor-notes](https://github.com/exercism/website-copy/pulls?q=is%3Aopen+is%3Apr+label%3Atype%2Fmentor-notes) before you start as well!

**Comment by SleeplessByte** [comment]
Almost there 🎉 🚀 🔥 ⏩

**Comment by SleeplessByte** [comment]
All core exercises currently have mentor notes or pending pull requests.

**Comment by tejasbubane** [comment]
Great job @SleeplessByte 👍

**Comment by SleeplessByte** [comment]
Reopened pr #650 #649 #648 and #642
