### ISSUE TITLE
Checklist: drop eslint for exercises

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#620]
Per #589,

- [x] move `eslint` config from root `package.json` into root `.eslintrc`
- [x] **remove** all `eslint` dependencies from exercise-level `package.json`
- [x] fix CI check to ignore eslint discrepancy between root and exercise-level `package.json` 
- [x] (optional): add script to add `eslint:recommended` to exercise-level `package.json` on "deploy".

**Comment by drericrobinson** [comment]
I'm happy to take this one, but I'm new to contributing so I'll need some direction on the third checkbox.

**Comment by SleeplessByte** [comment]
Hi @drericrobinson; this is in the works! However we could use a _lot_ of help [here](https://github.com/exercism/javascript/issues/628#issuecomment-473068089).

**Comment by SleeplessByte** [comment]
#645
