### ISSUE TITLE
Checklist: new exercises, currently not implemented

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#660]
- [ ] [affine-cipher](https://github.com/exercism/problem-specifications/tree/master/exercises/affine-cipher)
- [ ] [bank-account](https://github.com/exercism/problem-specifications/tree/master/exercises/bank-account)
- [ ] [book-store](https://github.com/exercism/problem-specifications/tree/master/exercises/book-store)
- [ ] [counter](https://github.com/exercism/problem-specifications/tree/master/exercises/counter)
- [ ] [dnd-character](https://github.com/exercism/problem-specifications/tree/master/exercises/dnd-character)
- [ ] [dominoes](https://github.com/exercism/problem-specifications/tree/master/exercises/dominoes)
- [ ] [dot-dsl](https://github.com/exercism/problem-specifications/tree/master/exercises/dot-dsl)
- [ ] [error-handling](https://github.com/exercism/problem-specifications/tree/master/exercises/error-handling)
- [ ] [go-counting](https://github.com/exercism/problem-specifications/tree/master/exercises/go-counting)
- [ ] [grep](https://github.com/exercism/problem-specifications/tree/master/exercises/grep)
- [ ] [hangman](https://github.com/exercism/problem-specifications/tree/master/exercises/hangman)
- [ ] [knapsack](https://github.com/exercism/problem-specifications/tree/master/exercises/knapsack)
- [ ] [ledger](https://github.com/exercism/problem-specifications/tree/master/exercises/ledger)
- [ ] [lens-person](https://github.com/exercism/problem-specifications/tree/master/exercises/lens-person)
- [ ] [markdown](https://github.com/exercism/problem-specifications/tree/master/exercises/markdown)
- [ ] [nucleotide-codons](https://github.com/exercism/problem-specifications/tree/master/exercises/nucleotide-codons)
- [ ] [paasio](https://github.com/exercism/problem-specifications/tree/master/exercises/paasio)
- [ ] [parallel-letter-frequency](https://github.com/exercism/problem-specifications/tree/master/exercises/parallel-letter-frequency)
- [ ] [poker](https://github.com/exercism/problem-specifications/tree/master/exercises/poker)
- [ ] [pov](https://github.com/exercism/problem-specifications/tree/master/exercises/pov)
- [ ] [rail-fence-cipher](https://github.com/exercism/problem-specifications/tree/master/exercises/rail-fence-cipher)
- [ ] [rest-api](https://github.com/exercism/problem-specifications/tree/master/exercises/rest-api)
- [ ] [satellite](https://github.com/exercism/problem-specifications/tree/master/exercises/satellite)
- [ ] [scale-generator](https://github.com/exercism/problem-specifications/tree/master/exercises/scale-generator)
- [ ] [sgf-parsing](https://github.com/exercism/problem-specifications/tree/master/exercises/sgf-parsing)
- [ ] [tournament](https://github.com/exercism/problem-specifications/tree/master/exercises/tournament)
- [ ] [tree-building](https://github.com/exercism/problem-specifications/tree/master/exercises/tree-building)
- [ ] [yacht](https://github.com/exercism/problem-specifications/tree/master/exercises/yacht)
- [ ] [zebra-puzzle](https://github.com/exercism/problem-specifications/tree/master/exercises/zebra-puzzle)

**Comment by tejasbubane** [comment]
The old version of exercism had a page showing unimplemented exercises for the language. I asked a question in slack if we have this page in the new version - someone said there is an issue created. We should probably get it back.

**Comment by SleeplessByte** [comment]
@tejasbubane yep, I saw that comment! So I thought, let me just create this list in the meantime :)

**Comment by tintinthong** [comment]
@SleeplessByte I will take `affine-cipher` I am currently doing it for the R track.

**Comment by mcampourcy** [comment]
@SleeplessByte Hi ! Can I take the `dnd-character` exercise ?

**Comment by tejasbubane** [comment]
@mcampourcy Go ahead 👍

**Comment by mcampourcy** [comment]
@SleeplessByte Actually, looks like it's already done :thinking: I'm gonna do the book store and change the issue title :)

**Comment by tejasbubane** [comment]
> Actually, looks like it's already done

Ahh, I did not check the already implemented ones. Let me quickly update the above list so others don't get confused :)

**Comment by tejasbubane** [comment]
Great, I have removed the checklist so that we don't have to manually maintain it.

**Comment by peterchu999** [comment]
@SleeplessByte Hi there i'm new in contributing but could help to make the `error-handling` exercise ?

**Comment by SleeplessByte** [comment]
Certainly! But perhaps you want to help out with next version of the track instead?

You can _check out_ [this issue](https://github.com/exercism/javascript/issues/850).

**Comment by peterchu999** [comment]
okay thanks, i'll that a quick look and see what i can help

**Comment by junedev** [comment]
Closing this issue because it is outdated. Please refer to https://github.com/exercism/javascript/blob/main/CONTRIBUTING.md#new-exercise for instructions on how to add exercises.
