### ISSUE TITLE
Checklist: normalise topics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#667]
**Note**: the suggestions are generated automagically. If something is _actually_ missing, please open an issue at [problem-specifications](https://github.com/exercism/problem-specifications) to add the missing topics.

```
=> fetching config from ../exercism-javascript/config.json
=> reading topics from ..\problem-specifications\TOPICS.txt
```

<details>
  <summary>List of valid topics</summary>

Source: [#d28d6](https://github.com/exercism/problem-specifications/blob/d28d6a5f40bb19f6a5954b7bda3430f4089aa680/TOPICS.txt)
- `abstract_classes`
- `callbacks`
- `conditionals`
- `events`
- `equality`
- `exception_handling`
- `generics`
- `inheritance`
- `interfaces`
- `loops`
- `operator_overloading`
- `pattern_matching`
- `polymorphism`
- `recursion`
- `threading`
- `type_conversion`
- `variables`
- `arrays`
- `booleans`
- `classes`
- `dates`
- `discriminated_unions`
- `enumerations`
- `floating_point_numbers`
- `graphs`
- `integers`
- `lists`
- `maps`
- `matrices`
- `optional_values`
- `queues`
- `records`
- `sequences`
- `sets`
- `stacks`
- `strings`
- `structs`
- `time`
- `trees`
- `tuples`
- `algorithms`
- `bitwise_operations`
- `concurrency`
- `cryptography`
- `domain_specific_languages`
- `files`
- `filtering`
- `games`
- `globalization`
- `logic`
- `math`
- `memory_management`
- `networking`
- `parallelism`
- `parsing`
- `pattern_recognition`
- `performance`
- `randomness`
- `refactoring`
- `regular_expressions`
- `searching`
- `security`
- `sorting`
- `text_formatting`
- `transforming`
- `behavior_driven_development`
- `functional_programming`
- `object_oriented_programming`
- `reactive_programming`
- `test_driven_development`
</details>

## Exercises with non-standard topics

- [ ] [`hello-world`](https://github.com/exercism/javascript/tree/master/exercises/hello-world)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
- [ ] [`pangram`](https://github.com/exercism/javascript/tree/master/exercises/pangram)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`matrix`](https://github.com/exercism/javascript/tree/master/exercises/matrix)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `data_structures`
- [ ] [`bob`](https://github.com/exercism/javascript/tree/master/exercises/bob)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `polymorfism` (perhaps: `polymorphism`)
  - [ ] `unicode` (perhaps: `time`, `records`)
- [ ] [`pascals-triangle`](https://github.com/exercism/javascript/tree/master/exercises/pascals-triangle)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`linked-list`](https://github.com/exercism/javascript/tree/master/exercises/linked-list)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `data_structures`
- [ ] [`list-ops`](https://github.com/exercism/javascript/tree/master/exercises/list-ops)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `data_structures`
- [ ] [`robot-name`](https://github.com/exercism/javascript/tree/master/exercises/robot-name)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
- [ ] [`simple-cipher`](https://github.com/exercism/javascript/tree/master/exercises/simple-cipher)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`wordy`](https://github.com/exercism/javascript/tree/master/exercises/wordy)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`secret-handshake`](https://github.com/exercism/javascript/tree/master/exercises/secret-handshake)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`reverse-string`](https://github.com/exercism/javascript/tree/master/exercises/reverse-string)
  Incorrect topics:
  - [ ] `for` (perhaps: `math`, `logic`, `files`, `time`, `sets`, `maps`, `loops`, `sorting`, `games`, `trees`, `records`, `lists`, `dates`, `arrays`)
- [ ] [`triangle`](https://github.com/exercism/javascript/tree/master/exercises/triangle)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`collatz-conjecture`](https://github.com/exercism/javascript/tree/master/exercises/collatz-conjecture)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`meetup`](https://github.com/exercism/javascript/tree/master/exercises/meetup)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`hamming`](https://github.com/exercism/javascript/tree/master/exercises/hamming)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`etl`](https://github.com/exercism/javascript/tree/master/exercises/etl)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`scrabble-score`](https://github.com/exercism/javascript/tree/master/exercises/scrabble-score)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`raindrops`](https://github.com/exercism/javascript/tree/master/exercises/raindrops)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
- [ ] [`allergies`](https://github.com/exercism/javascript/tree/master/exercises/allergies)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`nucleotide-count`](https://github.com/exercism/javascript/tree/master/exercises/nucleotide-count)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`grains`](https://github.com/exercism/javascript/tree/master/exercises/grains)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`word-count`](https://github.com/exercism/javascript/tree/master/exercises/word-count)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `unicode` (perhaps: `time`, `records`)
- [ ] [`perfect-numbers`](https://github.com/exercism/javascript/tree/master/exercises/perfect-numbers)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`luhn`](https://github.com/exercism/javascript/tree/master/exercises/luhn)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`pythagorean-triplet`](https://github.com/exercism/javascript/tree/master/exercises/pythagorean-triplet)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`difference-of-squares`](https://github.com/exercism/javascript/tree/master/exercises/difference-of-squares)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`prime-factors`](https://github.com/exercism/javascript/tree/master/exercises/prime-factors)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`palindrome-products`](https://github.com/exercism/javascript/tree/master/exercises/palindrome-products)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`acronym`](https://github.com/exercism/javascript/tree/master/exercises/acronym)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`series`](https://github.com/exercism/javascript/tree/master/exercises/series)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`largest-series-product`](https://github.com/exercism/javascript/tree/master/exercises/largest-series-product)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`bracket-push`](https://github.com/exercism/javascript/tree/master/exercises/bracket-push)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`saddle-points`](https://github.com/exercism/javascript/tree/master/exercises/saddle-points)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`ocr-numbers`](https://github.com/exercism/javascript/tree/master/exercises/ocr-numbers)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`spiral-matrix`](https://github.com/exercism/javascript/tree/master/exercises/spiral-matrix)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `data_structures`
- [ ] [`rectangles`](https://github.com/exercism/javascript/tree/master/exercises/rectangles)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`beer-song`](https://github.com/exercism/javascript/tree/master/exercises/beer-song)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`pig-latin`](https://github.com/exercism/javascript/tree/master/exercises/pig-latin)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`proverb`](https://github.com/exercism/javascript/tree/master/exercises/proverb)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`house`](https://github.com/exercism/javascript/tree/master/exercises/house)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`twelve-days`](https://github.com/exercism/javascript/tree/master/exercises/twelve-days)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `polymorfism` (perhaps: `polymorphism`)
- [ ] [`say`](https://github.com/exercism/javascript/tree/master/exercises/say)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`isbn-verifier`](https://github.com/exercism/javascript/tree/master/exercises/isbn-verifier)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`diamond`](https://github.com/exercism/javascript/tree/master/exercises/diamond)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`word-search`](https://github.com/exercism/javascript/tree/master/exercises/word-search)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`circular-buffer`](https://github.com/exercism/javascript/tree/master/exercises/circular-buffer)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `data_structures`
- [ ] [`binary-search`](https://github.com/exercism/javascript/tree/master/exercises/binary-search)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`binary-search-tree`](https://github.com/exercism/javascript/tree/master/exercises/binary-search-tree)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`custom-set`](https://github.com/exercism/javascript/tree/master/exercises/custom-set)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `data_structures`
- [ ] [`simple-linked-list`](https://github.com/exercism/javascript/tree/master/exercises/simple-linked-list)
  Incorrect topics:
  - [ ] `data_structures`
- [ ] [`two-bucket`](https://github.com/exercism/javascript/tree/master/exercises/two-bucket)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`bowling`](https://github.com/exercism/javascript/tree/master/exercises/bowling)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`connect`](https://github.com/exercism/javascript/tree/master/exercises/connect)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`strain`](https://github.com/exercism/javascript/tree/master/exercises/strain)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`accumulate`](https://github.com/exercism/javascript/tree/master/exercises/accumulate)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`sieve`](https://github.com/exercism/javascript/tree/master/exercises/sieve)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`nth-prime`](https://github.com/exercism/javascript/tree/master/exercises/nth-prime)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`atbash-cipher`](https://github.com/exercism/javascript/tree/master/exercises/atbash-cipher)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`crypto-square`](https://github.com/exercism/javascript/tree/master/exercises/crypto-square)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`diffie-hellman`](https://github.com/exercism/javascript/tree/master/exercises/diffie-hellman)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`rotational-cipher`](https://github.com/exercism/javascript/tree/master/exercises/rotational-cipher)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
- [ ] [`kindergarten-garden`](https://github.com/exercism/javascript/tree/master/exercises/kindergarten-garden)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`robot-simulator`](https://github.com/exercism/javascript/tree/master/exercises/robot-simulator)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`sum-of-multiples`](https://github.com/exercism/javascript/tree/master/exercises/sum-of-multiples)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`run-length-encoding`](https://github.com/exercism/javascript/tree/master/exercises/run-length-encoding)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
- [ ] [`roman-numerals`](https://github.com/exercism/javascript/tree/master/exercises/roman-numerals)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`queen-attack`](https://github.com/exercism/javascript/tree/master/exercises/queen-attack)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`all-your-base`](https://github.com/exercism/javascript/tree/master/exercises/all-your-base)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`protein-translation`](https://github.com/exercism/javascript/tree/master/exercises/protein-translation)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`trinary`](https://github.com/exercism/javascript/tree/master/exercises/trinary)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `mathematics` (perhaps: `math`)
- [ ] [`octal`](https://github.com/exercism/javascript/tree/master/exercises/octal)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `mathematics` (perhaps: `math`)
- [ ] [`hexadecimal`](https://github.com/exercism/javascript/tree/master/exercises/hexadecimal)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `mathematics` (perhaps: `math`)
- [ ] [`binary`](https://github.com/exercism/javascript/tree/master/exercises/binary)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
  - [ ] `mathematics` (perhaps: `math`)

## Exercises without topics

- [ ] [`darts`](https://github.com/exercism/javascript/tree/master/exercises/darts)
- [ ] [`point-mutations`](https://github.com/exercism/javascript/tree/master/exercises/point-mutations)

**Comment by alirezaghey** [comment]
Hey @SleeplessByte 
I saw _"polymorfism"_ on the JS track and landed here trying to figure out where it is set and how I can change it.
Do you mind if I take this one?
I'm relatively new and may need a little bit of hand-holding.

**Comment by SleeplessByte** [comment]
Take it :heart:. Let me know what you need.

**Comment by alirezaghey** [comment]
Great!
I see this is in the `./config.json` file.
I'm going to edit the file and do a PR.
Or do you need to assign the task to me?

**Comment by SleeplessByte** [comment]
Nope, this suffices!
