### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/javascript#966]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/javascript/issues/957)
- [x] [Add key features](https://github.com/exercism/javascript/issues/958)
- [x] [Add tags](https://github.com/exercism/javascript/issues/959)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/javascript/issues/960)
- [x] [Update status of track](https://github.com/exercism/javascript/issues/964)
- [x] [Update status of Concept Exercises](https://github.com/exercism/javascript/issues/965)
- [x] [Pass linting checks](https://github.com/exercism/javascript/issues/961)
- [x] [Build Test Runner](https://github.com/exercism/javascript/issues/962)
- [x] [Build Analyzer and Representer](https://github.com/exercism/javascript/issues/963) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/javascript/issues/1028)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by junedev** [comment]
The remaining open items are mentioned in other issues.
